ENGLISH_KEYWORDS = [
    # Single-word insults
    "stupid",
    "idiot",
    "dumb",
    "fool",
    "moron",
    "loser",
    "brat",
    "jerk",
    "trash",
    "pathetic",
    "worthless",
    "ignorant",
    "lazy",
    "useless",
    "coward",
    "weakling",
    "clueless",
    "awful",
    "horrible",
    "terrible",
    "disgusting",
    "gross",
    "nasty",
    "ugly",
    "creep",
    "silly",
    "dunce",
    "incompetent",
    "obnoxious",
    "annoying",
    "repulsive",
    "ridiculous",
    "absurd",
    "lame",
    "vile",
    "harsh",
    "rude",
    "insane",
    "insanity",
    "crazy",
    "psycho",
    "freak",
    "idiotic",
    "demonic",
    "disrespectful",
    "ungrateful",
    "useless",
    
    # Multi-word insults / phrases
    "shut up",
    "shut it",
    "zip it",
    "be quiet",
    "stop crying",
    "stop whining",
    "stop that",
    "cut it out",
    "grow up",
    "get lost",
    "nobody cares",
    "no one cares",
    "mindless fool",
    "stupid kid",
    "stop screaming",
    "crybaby",
    "stop acting up",
    "stop bothering me",
    
    # Harsh commands
    "leave me alone",
    "go away",
    "quiet down",
    "knock it off",
    "quit whining",
    
    # Derogatory name-calling
    "good for nothing",
    "worthless piece",
    "waste of time",
    "waste of space",
    "nobody likes you",
    
    # Minimizing or belittling language
    "why are you so dumb",
    "you know nothing",
    "you can’t do anything right",
    "you’re worthless",
    "what’s wrong with you",
    "you’re hopeless",
    
    # Aggressive / threatening
    "or else",
    "i’ll make you",
    "shut your mouth",
    "watch yourself",
    "you’ll regret it",
    
    # Swearing / profanity (mild examples; expand as needed)
    "damn you",
    "what the hell",
    "bloody hell",        # more common in British English
    "holy crap",
    "fricking",
    "freaking",
    
    # Demeaning statements
    "nobody wants you",
    "nobody loves you",
    "you’re a burden",
    "you’re nothing",
    "you’re pathetic",
    
    # Commands that demean autonomy
    "do as i say",
    "obey me",
    "listen up",
    "shut your face",
    "don’t talk back",
    
    # Degrading statements
    "you’re such a failure",
    "you’ll never learn",
    "you’re a big mess",
    "you can’t do anything",
    
    # Additional variations or synonyms
    "dummy",
    "blockhead",
    "dullard",
    "thickheaded",
    "boneheaded",
    "scatterbrain",
    "feeble-minded",
    "simple-minded",
    "two-faced",
    "hypocrite",
    "idiotic brat",
    "crying baby",
    "little monster",
    "spoiled brat",
    "smart aleck",
    "good-for-nothing",
    "lowlife",
    "vermin",
    "loudmouth",
    "hard-headed",
    "greedy",
    "useless brat",
    "stop messing around",
    "stop messing with me",
    "what’s your problem",
    "what’s your issue",
    "can’t you do anything right",
    "no one asked you",
    "shut your trap",
    "pipe down"
]

HEBREW_KEYWORDS = [
    "אלימות", "אלים", "בריונות", "בריון", "הצקה", "מציק", "מְצִיקָה", 
    "מכה", "מכות", "מַכָּה", "להרביץ", "דחיפה", "דוחף", 
    "בכי", "בוכה", "בכיתי", 
    "פחד", "מפחיד", "מפחד", "מבועת", 
    "כאב", "כואב", 
    "השפלה", "משפיל", "משפילה", "משפיל/ה", 
    "עלבון", "נעלב", "נעלבת", 
    "עלוב", "עצוב", "עצב", 
    "צעקה", "צעקות", "צורח", "צורחת", 
    "קללה", "קללות", "מילה גסה", "מילים גסות", 
    "לא נעים", "רע לי", 
    "סכנה", "מסוכן", "איום", "מאיים", 
    "לא בסדר", "בלתי נסבל", 
    "חרם", "דחייה", 
    "הטרדה", "הטרדה מינית", 
    "התעללות", "להתעלל", "מתעלל", "מתעללת", 
    "מגע לא מתאים", "פגיעה מינית", "אונס", "סוטה", 
    "סוד", "אל תספר", "תשתוק", "תהיה בשקט", 
    "שקר", "שקרן", "רמאות", 
    "גניבה", "לגנוב", "גנב", 
    "חרדה", "חרד", "דיכאון", "מדוכא", 
    "לחץ", "לחוץ", 
    "עצבים", "עצבני", 
    "בושה", "מבושה", 
    "ניכור", "בדידות", 
    "צרח", "צרחות", 
    "דחף", "דחיפה", 
    "משיכה בשיער", "נשיכה", "צביטה", 
    "חניקה", "חונק", 
    "אובדן", "אבוד", 
    "מושפל", "מושפלת", 
    "בוגד", "בגידה", 
    "מבוהל", "בהלה", 
    "מנודה", 
    "כינוי גנאי", "כינויים מעליבים", 
    "גועל", "מגעיל", "דוחה", 
    "סחיטה", 
    "שנאה", "שונא", "שונאת", 
    "רוע", "רשע", "רשעיות", 
    "מניאק", "מניאקית", 
    "אין כניסה", "אל תבוא", 
    "דחוי", "מתרחק", 
    "קנאה", "קנאי", 
    "רכילות", 
    "פגוע", "פגועה", 
    "מערער", 
    "מוות", "למות", 
    "נדקר", "דקירה", 
    "שבועה", "נשבע", "משקר", 
    "גזענות", "גזען", 
    "עונש", "נענש", 
    "פגיעה", "פגוע", 
    "סוטר", "סטירה", "סטירות", 
    "מתחבא", "מסתתר",
]

